// const/travelDeals.ts
export const generateImagePath = (countryKey: string, indexImg: number) => {
  // Use country_key and indexImg to construct the image path
  const imagePath = `/countries/${countryKey}/${countryKey}_${indexImg}.jpg`;
  // Fallback to placeholder if needed
  return imagePath || "/api/placeholder/300/200";
};

export const travelDeals = [
  {
    country: "Болгарія",
    country_key: "bulgaria",
    price: 125,
    discount: "-20%",
    indexImg: 1,
  },
  {
    country: "Болгарія",
    country_key: "bulgaria",
    price: 397,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Болгарія",
    country_key: "bulgaria",
    price: 443,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Болгарія",
    country_key: "bulgaria",
    price: 551,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 892,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1278,
    discount: "-15%",
    indexImg: 2,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1544,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1582,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1610,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1723,
    discount: "-25%",
    indexImg: 6,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1771,
    discount: null,
    indexImg: 7,
  },
  {
    country: "Домінікана",
    country_key: "dominica",
    price: 1900,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 173,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 186,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 193,
    discount: "-25%",
    indexImg: 3,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 206,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 238,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 273,
    discount: "-20%",
    indexImg: 6,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 273,
    discount: "-50%",
    indexImg: 7,
  },
  {
    country: "Єгипет",
    country_key: "egipt",
    price: 334,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Ізраїль",
    country_key: "israel",
    price: 391,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Ізраїль",
    country_key: "israel",
    price: 567,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Ізраїль",
    country_key: "israel",
    price: 871,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Ізраїль",
    country_key: "israel",
    price: 891,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 415,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 511,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 521,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 610,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 731,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 733,
    discount: null,
    indexImg: 6,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 885,
    discount: null,
    indexImg: 7,
  },
  {
    country: "Індія",
    country_key: "india",
    price: 1014,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Іспанія",
    country_key: "spain",
    price: 501,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Іспанія",
    country_key: "spain",
    price: 562,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Іспанія",
    country_key: "spain",
    price: 704,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Іспанія",
    country_key: "spain",
    price: 1036,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Кіпр",
    country_key: "kipr",
    price: 484,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Кіпр",
    country_key: "kipr",
    price: 505,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Кіпр",
    country_key: "kipr",
    price: 565,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Кіпр",
    country_key: "kipr",
    price: 565,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Кіпр",
    country_key: "kipr",
    price: 957,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 1020,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 1139,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 1535,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 1669,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 1765,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 1848,
    discount: null,
    indexImg: 6,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 2045,
    discount: "-35%",
    indexImg: 7,
  },
  {
    country: "Мальдіви",
    country_key: "maldivy",
    price: 2325,
    discount: null,
    indexImg: 8,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 249,
    discount: "-25%",
    indexImg: 1,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 311,
    discount: null,
    indexImg: 2,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 331,
    discount: null,
    indexImg: 3,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 317,
    discount: null,
    indexImg: 4,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 417,
    discount: null,
    indexImg: 5,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 447,
    discount: null,
    indexImg: 6,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 449,
    discount: null,
    indexImg: 7,
  },
  {
    country: "ОАЕ",
    country_key: "oae",
    price: 519,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Греція",
    country_key: "greece",
    price: 354,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Греція",
    country_key: "greece",
    price: 445,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Греція",
    country_key: "greece",
    price: 1443,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Греція",
    country_key: "greece",
    price: 2023,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 779,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 781,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 831,
    discount: "-20%",
    indexImg: 3,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 844,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 978,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 987,
    discount: null,
    indexImg: 6,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 1002,
    discount: null,
    indexImg: 7,
  },
  {
    country: "Таїланд",
    country_key: "thailand",
    price: 1286,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 794,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 857,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 895,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 925,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 986,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 1005,
    discount: null,
    indexImg: 6,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 1156,
    discount: null,
    indexImg: 7,
  },
  {
    country: "Танзанія",
    country_key: "tanxania",
    price: 1313,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Туніс",
    country_key: "tunis",
    price: 318,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Туніс",
    country_key: "tunis",
    price: 359,
    discount: "-15%",
    indexImg: 2,
  },
  {
    country: "Туніс",
    country_key: "tunis",
    price: 493,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Туніс",
    country_key: "tunis",
    price: 500,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 258,
    discount: "-20%",
    indexImg: 1,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 283,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 283,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 341,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 345,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 346,
    discount: null,
    indexImg: 6,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 379,
    discount: null,
    indexImg: 7,
  },
  {
    country: "Туреччина",
    country_key: "turkey",
    price: 392,
    discount: null,
    indexImg: 8,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 580,
    discount: null,
    indexImg: 1,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 596,
    discount: null,
    indexImg: 2,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 623,
    discount: null,
    indexImg: 3,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 626,
    discount: null,
    indexImg: 4,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 739,
    discount: null,
    indexImg: 5,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 757,
    discount: null,
    indexImg: 6,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 783,
    discount: null,
    indexImg: 7,
  },
  {
    country: "Шрі Ланка",
    country_key: "shri-lanka",
    price: 828,
    discount: null,
    indexImg: 8,
  },
].map((deal, index) => ({
  ...deal,
  id: index + 1,
  image: generateImagePath(deal.country_key, deal.indexImg),
}));
